//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Network_DataDefs_NetMsgDef_SPMPSWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Network.DataDefs.NetMsgDef.SPMPS), typeof(System.Object));
		L.RegFunction("New", _CreateNetwork_DataDefs_NetMsgDef_SPMPS);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("EPRO_MOVE_MESSAGE", 32);
		L.RegConstant("EPRO_CHAT_MESSAGE", 33);
		L.RegConstant("EPRO_FIGHT_MESSAGE", 34);
		L.RegConstant("EPRO_SCRIPT_MESSAGE", 35);
		L.RegConstant("EPRO_REGION_MESSAGE", 36);
		L.RegConstant("EPRO_ITEM_MESSAGE", 37);
		L.RegConstant("EPRO_SYSTEM_MESSAGE", 38);
		L.RegConstant("EPRO_UPGRADE_MESSAGE", 39);
		L.RegConstant("EPRO_TEAM_MESSAGE", 40);
		L.RegConstant("EPRO_TONG_MESSAGE", 41);
		L.RegConstant("EPRO_MENU_MESSAGE", 42);
		L.RegConstant("EPRO_RELATION_MESSAGE", 43);
		L.RegConstant("EPRO_HEROS_MESSAGE", 52);
		L.RegConstant("EPRO_CHKREBIND_MESSAGE", 100);
		L.RegConstant("EPRO_COLLECT_MESSAGE", 208);
		L.RegConstant("EPRO_GAMEMNG_MESSAGE", 224);
		L.RegConstant("EPRO_GMM_MESSAGE", 225);
		L.RegConstant("EPRO_REFRESH_MESSAGE", 240);
		L.RegConstant("EPRO_SERVER_CONTROL", 241);
		L.RegConstant("EPRO_REBIND_MESSAGE", 242);
		L.RegConstant("EPRO_DATABASE_MESSAGE", 243);
		L.RegConstant("EPRO_ACCOUNT_MESSAGE", 244);
		L.RegConstant("EPRO_ORB_MESSAGE", 245);
		L.RegConstant("EPRO_DATATRANS_MESSAGE", 246);
		L.RegConstant("EPRO_DBOP_MESSAGE", 247);
		L.RegConstant("EPRO_POINTMODIFY_MESSAGE", 248);
		L.RegConstant("EPRO_MAIL_MESSAGE", 249);
		L.RegConstant("EPRO_EMAIL_MESSAGE", 250);
		L.RegConstant("EPRO_UNION_MESSAGE", 251);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNetwork_DataDefs_NetMsgDef_SPMPS(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Network.DataDefs.NetMsgDef.SPMPS obj = new Network.DataDefs.NetMsgDef.SPMPS();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Network.DataDefs.NetMsgDef.SPMPS.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

