//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Network_DataDefs_NetMsgDef_SCMPSWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Network.DataDefs.NetMsgDef.SCMPS), typeof(System.Object));
		L.RegFunction("New", _CreateNetwork_DataDefs_NetMsgDef_SCMPS);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("EPRO_LOGIN", 0);
		L.RegConstant("EPRO_CREATE_CHARACTER", 1);
		L.RegConstant("EPRO_DEL_CHARACTER", 2);
		L.RegConstant("EPRO_SELECT_CHARACTER", 3);
		L.RegConstant("EPRO_LOGOUT", 4);
		L.RegConstant("EPRO_CHARACTER_LIST_INFO", 5);
		L.RegConstant("EPRO_CHARACTER_DATA_INFO", 6);
		L.RegConstant("EPRO_LOGIN_NOCHECKACCOUNT", 7);
		L.RegConstant("EPRO_PREVENT_INDULGE", 9);
		L.RegConstant("EPRO_CLIENT_REQUEST_RPCOP", 11);
		L.RegConstant("EPRO_STORY_STEP", 12);
		L.RegConstant("EPRO_REBIND_REGION_SERVER", 0);
		L.RegConstant("EPRO_CHECK_REBIND", 1);
		L.RegConstant("EPRO_REBIND_LOGIN_SERVER", 2);
		L.RegConstant("EPRO_SYN_WAYTRACK", 0);
		L.RegConstant("EPRO_SYN_POSITION", 1);
		L.RegConstant("EPRO_SET_ZAZEN", 2);
		L.RegConstant("EPRO_SYN_WAYJUMP", 3);
		L.RegConstant("EPRO_LOCK_PLAYER", 4);
		L.RegConstant("EPRO_SYN_DIRECTION", 5);
		L.RegConstant("EPRO_SET_FLY", 6);
		L.RegConstant("EPRO_MOVE_OBJECT", 0);
		L.RegConstant("EPRO_DEL_OBJECT", 0);
		L.RegConstant("EPRO_SYN_PLAYER_INFO", 1);
		L.RegConstant("EPRO_SYN_NPC_INFO", 2);
		L.RegConstant("EPRO_SYN_MONSTER_INFO", 3);
		L.RegConstant("EPRO_SET_EFFECT", 4);
		L.RegConstant("EPRO_OBJECT_INFO", 5);
		L.RegConstant("EPRO_SET_REGION", 6);
		L.RegConstant("EPRO_SYN_OBJECT", 7);
		L.RegConstant("EPRO_SETEXTRASTATE", 8);
		L.RegConstant("EPRO_SYN_PLAYER_IS_TEAM_INFO", 10);
		L.RegConstant("EPRO_SYN_AREAGIDS", 11);
		L.RegConstant("EPRO_SYN_MUTATE_POS", 12);
		L.RegConstant("EPRO_SYN_MONSTER_INFO_EX", 13);
		L.RegConstant("EPRO_SYN_PLAYER_INFO_EX", 14);
		L.RegConstant("EPRO_SYN_HERO_DATA", 15);
		L.RegConstant("EPRO_SYN_MOUNTS", 16);
		L.RegConstant("EPRO_SEND_PLAYLIST", 17);
		L.RegConstant("EPRO_RES_CHANGE", 0);
		L.RegConstant("EPRO_BUFF_UPDATE", 1);
		L.RegConstant("EPRO_PLAYER_ATTRI", 2);
		L.RegConstant("EPRO_SKILL_CHANGE", 3);
		L.RegConstant("EPRO_TELERGY_CHANGE", 4);
		L.RegConstant("EPRO_BUFF_SPLITMOVE", 5);
		L.RegConstant("EPRO_BUFF_DAMAGE_INFO_SHOW", 6);
		L.RegConstant("EPRO_MOVESPEED_CHANGE", 7);
		L.RegConstant("EPRO_EXP_CHANGE", 8);
		L.RegConstant("EPRO_BUFF_PRO_SYN_TO_SELECT", 9);
		L.RegConstant("EPRO_BUFF_EFFECT_SYN_TO_ALL", 10);
		L.RegConstant("EPRO_MULTIPLICITY_EXP", 11);
		L.RegConstant("EPRO_SET_TASK_MASK", 12);
		L.RegConstant("EPRO_SET_TONG_NAME", 13);
		L.RegConstant("EPRO_UPDATE_LEVELUP", 14);
		L.RegConstant("EPRO_UPDATE_GIFT", 15);
		L.RegConstant("EPRO_UPDATE_EQUIPCOUNT", 16);
		L.RegConstant("EPRO_DROP_ITEM", 0);
		L.RegConstant("EPRO_PICKUP_ITEM", 1);
		L.RegConstant("EPRO_ADDPACKAGE_ITEM", 2);
		L.RegConstant("EPRO_ADDWAREHOUSE_ITEM", 3);
		L.RegConstant("EPRO_ADDGROUND_ITEM", 4);
		L.RegConstant("EPRO_PRE_USE_ITEM", 5);
		L.RegConstant("EPRO_USE_ITEM", 6);
		L.RegConstant("EPRO_DELPACKAGE_ITEM", 7);
		L.RegConstant("EPRO_DELGROUND_ITEM", 8);
		L.RegConstant("EPRO_MOVE_ITEM", 9);
		L.RegConstant("EPRO_EQUIP_ITEM", 10);
		L.RegConstant("RPRO_EQUIP_INFO", 11);
		L.RegConstant("RPRO_WAREHOUSE_BASE", 12);
		L.RegConstant("RPRO_EQUIPMENTINFO", 13);
		L.RegConstant("EPRO_AUTOUSE_ITEM", 14);
		L.RegConstant("EPRO_SPLIT_ITEM", 15);
		L.RegConstant("EPRO_NEATEN", 16);
		L.RegConstant("EPRO_UPDATE_TEMPITEM", 17);
		L.RegConstant("EPRO_USE_ITEM_CONFIRM", 18);
		L.RegConstant("ERPO_USE_RELIVEITEM_COUNT", 20);
		L.RegConstant("EPRO_ADD_PACK_OPENFLAGS", 19);
		L.RegConstant("ERPO_ADD_TEMPITEM_INFO", 21);
		L.RegConstant("EPRO_TEMPITEM_BROADCAST", 22);
		L.RegConstant("EPRO_SEND_JEWELLEVEL", 23);
		L.RegConstant("EPRO_USEINTERVAL_EFFECT", 24);
		L.RegConstant("EPRO_SYN_MONEY", 25);
		L.RegConstant("RPRO_OPEN_WAREHOUSE", 0);
		L.RegConstant("RPRO_CLOSE_WAREHOUSE", 1);
		L.RegConstant("RPRO_ITEM_MOVEIN", 2);
		L.RegConstant("RPRO_ITEM_MOVEOUT", 3);
		L.RegConstant("RPRO_ITEM_MOVESELF", 4);
		L.RegConstant("RPRO_ITEM_LOCKIT", 5);
		L.RegConstant("RPRO_ITEM_ARRANGE", 6);
		L.RegConstant("RPRO_MOVETO_ITEM", 0);
		L.RegConstant("EPRO_ADDSALE_ITEM", 1);
		L.RegConstant("EPRO_DELSALE_ITEM", 2);
		L.RegConstant("EPRO_SEESALE_ITEM", 3);
		L.RegConstant("EPRO_BUYSALE_ITEM", 4);
		L.RegConstant("EPRO_CLOSESALE_ITEM", 5);
		L.RegConstant("EPRO_UPDATESALE_ITEM", 6);
		L.RegConstant("EPRO_SEND_SALEINFO", 7);
		L.RegConstant("EPRO_REQUEST_STALLLIST", 9);
		L.RegConstant("EPRO_STALLLIST_NEXTPAGE", 10);
		L.RegConstant("EPRO_SHOW_STALLLIST", 11);
		L.RegConstant("EPRO_SHOW_GOODSLIST", 12);
		L.RegConstant("EPRO_CLICK_OBJECT", 0);
		L.RegConstant("EPRO_BACK_MSG", 1);
		L.RegConstant("EPRO_LUACUSTOM_MSG", 2);
		L.RegConstant("EPRO_SYNCTASKDATA", 3);
		L.RegConstant("EPRO_PROCESSACTION", 4);
		L.RegConstant("EPRO_WOUND_OBJECTEX", 0);
		L.RegConstant("EPRO_SWITCH_TO_SKILL_ATTACK_STATE", 1);
		L.RegConstant("EPRO_NOTIFY_START_COLD_TIMER", 2);
		L.RegConstant("EPRO_MOVE_TO_TARGET_FOR_ATTACK", 3);
		L.RegConstant("EPRO_QUEST_SKILL", 4);
		L.RegConstant("EPRO_SHOW_SKILL_HINT_INFO", 5);
		L.RegConstant("EPRO_SELECT_TARGET", 6);
		L.RegConstant("EPRO_SETBUFFICON_CHANGE", 7);
		L.RegConstant("EPRO_SETPROGRESS", 8);
		L.RegConstant("EPRO_CANCELPROGRESS", 9);
		L.RegConstant("EPRO_UPDATEBUFF_INFO", 10);
		L.RegConstant("EPRO_ENDPROGRESS", 11);
		L.RegConstant("EPRO_SET_OBJ_STATE", 12);
		L.RegConstant("EPRO_SET_BF_STATE", 13);
		L.RegConstant("EPRO_BF_ATTACK_MONSTER", 14);
		L.RegConstant("EPRO_FORCE_QUEST_ENEMY_INFO", 15);
		L.RegConstant("SANoticeHeroDead", 16);
		L.RegConstant("EPRO_REFRESH_PLAYER", 1);
		L.RegConstant("EPRO_ADD_MOUNTS", 0);
		L.RegConstant("EPRO_SET_HUNGER", 1);
		L.RegConstant("EPRO_FEED_MOUNTS", 2);
		L.RegConstant("EPRO_SET_EXP", 3);
		L.RegConstant("EPRO_SET_MOUNTS", 4);
		L.RegConstant("EPRO_SYNPLAYMOUNT_ACTION", 5);
		L.RegConstant("EPRO_OPERATE_MOUNTS", 6);
		L.RegConstant("EPRO_ADD_MOUNTSKILL", 7);
		L.RegConstant("EPRO_ADD_QUALITY", 8);
		L.RegConstant("EPRO_UPDATE_WUXING", 9);
		L.RegConstant("EPRO_ADD_MYTHAGO", 0);
		L.RegConstant("EPRO_OPERATE_MYTHAGO", 1);
		L.RegConstant("EPRO_SET_MYTHAGO_EXP", 2);
		L.RegConstant("EPRO_SET_MYTHAGO", 3);
		L.RegConstant("EPRO_SYN_MYTHAGO_ACTION", 4);
		L.RegConstant("EPRO_SET_MYTHAGO_POINT", 5);
		L.RegConstant("EPRO_SYN_MYTHAGO_POINT", 6);
		L.RegConstant("EPRO_SYN_MYTHAGO_LQ", 7);
		L.RegConstant("EPRO_TEAM_REFRESH", 0);
		L.RegConstant("EPRO_TEAM_JOIN", 1);
		L.RegConstant("EPRO_TEAM_KICK", 2);
		L.RegConstant("EPRO_TEAM_HEADMEN", 3);
		L.RegConstant("EPRO_TEAM_BREAK", 4);
		L.RegConstant("EPRO_TEAM_SUC_JOIN", 5);
		L.RegConstant("EPRO_TEAM_SYN_BUFF_ICON", 6);
		L.RegConstant("EPRO_ADD_RELATION", 0);
		L.RegConstant("EPRO_DEL_RELATION", 1);
		L.RegConstant("EPRO_REQUEST_ADD_RELATION", 2);
		L.RegConstant("EPRO_FRIEND_STATE", 3);
		L.RegConstant("EPRO_FRIEND_FIGHT", 4);
		L.RegConstant("EPRO_FRIEND_LEVELUP", 5);
		L.RegConstant("EPRO_FRIEND_SYN_DEARVALUE", 6);
		L.RegConstant("EPRO_ADD_HERO", 0);
		L.RegConstant("EPRO_OPERATE_HEROS", 1);
		L.RegConstant("EPRO_SYN_HERO_POS", 3);
		L.RegConstant("EPRO_SYNPLAYHERO_ACTION", 4);
		L.RegConstant("EPRO_SET_HEROSEXP", 5);
		L.RegConstant("EPRO_HERO_ATTRI", 6);
		L.RegConstant("EPRO_ADD_HEROSKILL", 7);
		L.RegConstant("EPRO_UP_ATT_ADD", 8);
		L.RegConstant("EPRO_UP_ATT_SURE", 9);
		L.RegConstant("EPRO_OVER_AUTO_ATTADD", 10);
		L.RegConstant("EPRO_CHANGE_NAME", 11);
		L.RegConstant("EPRO_USEITEM_TO_HERO", 12);
		L.RegConstant("EPRO_SET_LOGITY", 13);
		L.RegConstant("EPRO_UPDATE_HERO", 14);
		L.RegConstant("EPRO_UPDATE_HEROTECH_CD", 15);
		L.RegConstant("EPRO_CHAT_MSG", 0);
		L.RegConstant("EPRO_TIP_INFO", 1);
		L.RegConstant("EPRO_BUFF_IMM", 2);
		L.RegConstant("EPRO_CHAT_KILLED", 3);
		L.RegConstant("EPRO_TONG_INVITE_JOIN", 0);
		L.RegConstant("EPRO_TONG_SEND_INVITE_JOIN", 1);
		L.RegConstant("EPRO_TONG_QUEST_JOIN", 2);
		L.RegConstant("EPRO_TONG_RECV_RAPPLY_JOIN", 3);
		L.RegConstant("EPRO_TONG_MEMBER_MANAGER", 4);
		L.RegConstant("EPRO_INPUT_MEMO", 5);
		L.RegConstant("EPRO_TONG_MEMBER_UPDATE", 6);
		L.RegConstant("EPRO_TONG_DELETE", 7);
		L.RegConstant("EPRO_TONG_PRETIGE_RANKING", 8);
		L.RegConstant("EPRO_TONG_INITFACTION_INFO", 9);
		L.RegConstant("EPRO_TONG_UPDATA_FACTION_HEAD", 10);
		L.RegConstant("EPRO_QUEST_MEMBERLIST", 11);
		L.RegConstant("EPRO_MENU", 0);
		L.RegConstant("EPRO_INVITE_JOIN_TEAM", 1);
		L.RegConstant("EPRO_OTHEREQUIPMENTNAME", 2);
		L.RegConstant("EPRO_RELIVE_OP", 3);
		L.RegConstant("EPRO_SHOW_OUTEQUIP", 4);
		L.RegConstant("EPRO_BUFF_CLOSE_COSTUME", 5);
		L.RegConstant("RPRO_SET_HEROAI", 6);
		L.RegConstant("EPRO_CHAT_GETINFO", 7);
		L.RegConstant("EPRO_GET_FBLIST", 8);
		L.RegConstant("EPRO_SETPKRULE", 9);
		L.RegConstant("RPRO_QUEST_EXCHANGE", 0);
		L.RegConstant("RPRO_MOVE_EXCHANGE_ITEM", 1);
		L.RegConstant("RPRO_EXCHANGE_OPERATION", 2);
		L.RegConstant("RPRO_QUEST_REMOTE_EXCHANGE", 3);
		L.RegConstant("RPRO_DEL_EXCHANGE_ITEM", 4);
		L.RegConstant("EPRO_INVITE_EXCHANGE", 0);
		L.RegConstant("EPRO_UICLICK_DATA", 6);
		L.RegConstant("EPRO_CLICK_HP", 7);
		L.RegConstant("EPRO_MAIL_SEND", 0);
		L.RegConstant("EPRO_MAIL_RECV", 1);
		L.RegConstant("EPRO_MAIL_DELETE", 2);
		L.RegConstant("EPRO_MAIL_NEWMAIL", 3);
		L.RegConstant("EPRO_BROADCAST", 4);
		L.RegConstant("EPRO_EMAIL_SEND", 0);
		L.RegConstant("EPRO_EMAIL_RECV", 1);
		L.RegConstant("EPRO_EMAIL_DELETE", 2);
		L.RegConstant("EPRO_EMAIL_NEWMAIL", 0);
		L.RegConstant("EPRO_EMAIL_SYSTEM", 4);
		L.RegConstant("EPRO_EMAIL_SETREAD", 5);
		L.RegConstant("EPRO_EMAIL_ADDITEM", 6);
		L.RegConstant("EPRO_EMAIL_MONEY", 7);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNetwork_DataDefs_NetMsgDef_SCMPS(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Network.DataDefs.NetMsgDef.SCMPS obj = new Network.DataDefs.NetMsgDef.SCMPS();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Network.DataDefs.NetMsgDef.SCMPS.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

