//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Network_DataDefs_LYBGlobalConstsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Network.DataDefs.LYBGlobalConsts), typeof(System.Object));
		L.RegFunction("random", random);
		L.RegFunction("New", _CreateNetwork_DataDefs_LYBGlobalConsts);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("ENCODE", get_ENCODE, null);
		L.RegConstant("PING", 1735289200);
		L.RegConstant("PONG", 1735290736);
		L.RegConstant("TICK", 1801677172);
		L.RegConstant("MAX_ROLENAMESIZE", 21);
		L.RegConstant("MAX_TONGNAMESIZE", 21);
		L.RegConstant("MAX_TITLENAMESIZE", 21);
		L.RegConstant("ITEM_HEAD_LENGTH", 7);
		L.RegConstant("ITEM_DATA_LENGTH", 38);
		L.RegConstant("ITEM_ALL_LENGTH", 50);
		L.RegConstant("MAX_EQUIP_COUNT", 16);
		L.RegConstant("MAX_SKILL_COUNT", 20);
		L.RegConstant("MAX_CITTA_COUNT", 16);
		L.RegConstant("MAX_TALNET_COUNT", 20);
		L.RegConstant("MAX_TRACK_LENGTH", 20);
		L.RegConstant("INVALID_ID", 184549376);
		L.RegConstant("PLAYER_VERSION", 215);
		L.RegVar("XYD_VERSION", get_XYD_VERSION, null);
		L.RegVar("ERROR_LOG_SERVER", get_ERROR_LOG_SERVER, null);
		L.RegConstant("CHAT_WIDTH", 219);
		L.RegConstant("ZOOM_NUM", 1);
		L.RegConstant("VIEWOBJ_WIDTH", 1920);
		L.RegConstant("VIEWOBJ_HEIGHT", 1080);
		L.RegConstant("VIEW_LEFT_OFFSET", 0);
		L.RegConstant("VIEW_TOP_OFFSET", 0);
		L.RegConstant("GRID_WIDTH", 64);
		L.RegConstant("GRID_HEIGHT", 32);
		L.RegConstant("SERVER_AREA_X", 8);
		L.RegConstant("SERVER_AREA_Y", 10);
		L.RegConstant("CHUNK_WIDTH", 512);
		L.RegConstant("CHUNK_HEIGHT", 512);
		L.RegConstant("AREA_SIZEX", 12);
		L.RegConstant("AREA_SIZEY", 16);
		L.RegVar("SCREEN_MAX_OBJECT", get_SCREEN_MAX_OBJECT, set_SCREEN_MAX_OBJECT);
		L.RegVar("SCREEN_MAX_PLAYER", get_SCREEN_MAX_PLAYER, set_SCREEN_MAX_PLAYER);
		L.RegConstant("ZONE_WIDTH", 1024);
		L.RegConstant("ZONE_HEIGHT", 640);
		L.RegConstant("BASE_SPEED", 100);
		L.RegConstant("MAX_ACCOUNT", 140);
		L.RegConstant("MAX_PASSWORD", 140);
		L.RegConstant("MAX_ACCAPASS", 1164);
		L.RegConstant("CONST_USERPASS", 21);
		L.RegConstant("PINGMARGIN", 15000);
		L.RegConstant("ST_ALEVEL", 0);
		L.RegConstant("ST_AMONEY", 1);
		L.RegConstant("ST_RFAME", 2);
		L.RegConstant("ST_LFAME", 3);
		L.RegConstant("MAX_MAILSIZE", 400);
		L.RegConstant("MAX_MAILTITLESIZE", 40);
		L.RegConstant("MAX_MAILITEMSIZE", 5);
		L.RegConstant("DEFAULT_NEAR_RADIUS", 2);
		L.RegConstant("LIFETYPE_BASEOBJECT", 0);
		L.RegConstant("LIFETYPE_BASEITEM", 1);
		L.RegConstant("LIFETYPE_BASELIFE", 2);
		L.RegConstant("LIFETYPE_FIGHTLIFE", 3);
		L.RegConstant("LIFETYPE_BASEPLAYER", 4);
		L.RegConstant("LIFETYPE_PLAYER", 5);
		L.RegConstant("LIFETYPE_NPC", 6);
		L.RegConstant("LIFETYPE_HEROS", 16);
		L.RegConstant("LIFETYPE_DROPITEM", 17);
		L.RegConstant("LIFETYPE_MONSTER", 7);
		L.RegConstant("LIFETYPE_BUILDING", 8);
		L.RegConstant("LIFETYPE_ROBOT", 9);
		L.RegConstant("IID_BASELIFE", 1);
		L.RegConstant("IID_BASESTATIC", 2);
		L.RegConstant("IID_MAPEFFECT", 3);
		L.RegConstant("IID_SKILLEFFECT", 4);
		L.RegConstant("IID_BASEPLAYER", 5);
		L.RegConstant("IID_PLAYER", 6);
		L.RegConstant("IID_NPC", 287375508);
		L.RegConstant("IID_MONSTER", 287375524);
		L.RegConstant("IID_ITEM", 292088596);
		L.RegConstant("IID_HEROS", 9);
		L.RegConstant("IID_CONTESTPLAYER", 7);
		L.RegConstant("IID_HORSE", 8);
		L.RegConstant("EA_STAND", 0);
		L.RegConstant("EA_WALK", 1);
		L.RegConstant("EA_RUN", 1);
		L.RegConstant("EA_JUMP", 2);
		L.RegConstant("EA_JUMP2", 40);
		L.RegConstant("EA_JUMP3", 45);
		L.RegConstant("EA_RUN2", 42);
		L.RegConstant("EA_ZAZEN", 3);
		L.RegConstant("EA_WOUND", 4);
		L.RegConstant("EA_DEAD", 5);
		L.RegConstant("EA_HIDE", 6);
		L.RegConstant("EA_ATTACK", 7);
		L.RegConstant("EA_ATTACK2", 51);
		L.RegConstant("EA_ATTACK3", 52);
		L.RegConstant("EA_PROGRESS", 8);
		L.RegConstant("EA_BEAT_FLAT", 9);
		L.RegConstant("EA_KNOCKOUT", 10);
		L.RegConstant("EA_AC_MAX", 11);
		L.RegConstant("EA_AC_NIL", 12);
		L.RegConstant("EA_RIDE", 15);
		L.RegConstant("EA_RIDEATTACK", 30);
		L.RegConstant("EA_RIDEATTACK2", 31);
		L.RegConstant("EA_RIDEWOUND", 22);
		L.RegConstant("EA_RIDESTAND", 23);
		L.RegConstant("EA_FLY", 24);
		L.RegConstant("EA_HORSEJUMP", 25);
		L.RegConstant("EA_STANDBIG", 41);
		L.RegConstant("EA_RUN3", 44);
		L.RegConstant("EA_VILLRun", 46);
		L.RegConstant("EA_SPRING_ATT", 10);
		L.RegConstant("EA_SPRING_JUMPUP", 2);
		L.RegConstant("EA_SPRING_JUMPDOWN", 12);
		L.RegConstant("EA_SPRING_PLAY", 13);
		L.RegConstant("EA_SPRING_STAND", 14);
		L.RegConstant("EA_PET1", 67);
		L.RegConstant("EA_PET2", 68);
		L.RegConstant("EA_PET3", 69);
		L.RegVar("EQ_STAND", get_EQ_STAND, null);
		L.RegVar("EQ_WALK", get_EQ_WALK, null);
		L.RegVar("EQ_RUN", get_EQ_RUN, null);
		L.RegVar("EQ_JUMP", get_EQ_JUMP, null);
		L.RegVar("EQ_JUMP2", get_EQ_JUMP2, null);
		L.RegVar("EQ_ZAZEN", get_EQ_ZAZEN, null);
		L.RegVar("EQ_ATTACKSTAND", get_EQ_ATTACKSTAND, null);
		L.RegVar("EQ_STANDBIG", get_EQ_STANDBIG, null);
		L.RegVar("EQ_ATTACK", get_EQ_ATTACK, null);
		L.RegVar("EQ_ATTACK2", get_EQ_ATTACK2, null);
		L.RegVar("EQ_ATTACK3", get_EQ_ATTACK3, null);
		L.RegVar("EQ_WOUND", get_EQ_WOUND, null);
		L.RegVar("EQ_DEAD", get_EQ_DEAD, null);
		L.RegVar("EQ_RIDE", get_EQ_RIDE, null);
		L.RegVar("EQ_RIDEATTACK", get_EQ_RIDEATTACK, null);
		L.RegVar("EQ_RIDEATTACK2", get_EQ_RIDEATTACK2, null);
		L.RegVar("EQ_RIDEWOUND", get_EQ_RIDEWOUND, null);
		L.RegVar("EQ_RIDSTAND", get_EQ_RIDSTAND, null);
		L.RegVar("EQ_FLY", get_EQ_FLY, null);
		L.RegVar("EQ_FLYSTAND", get_EQ_FLYSTAND, null);
		L.RegVar("EQ_HORSEJUMP", get_EQ_HORSEJUMP, null);
		L.RegVar("EQ_RUN2", get_EQ_RUN2, null);
		L.RegVar("EQ_RUN3", get_EQ_RUN3, null);
		L.RegVar("EQ_JUMP3", get_EQ_JUMP3, null);
		L.RegVar("EQ_VILLRun", get_EQ_VILLRun, null);
		L.RegVar("EQ_11", get_EQ_11, null);
		L.RegVar("EQ_12", get_EQ_12, null);
		L.RegVar("EQ_13", get_EQ_13, null);
		L.RegVar("EQ_14", get_EQ_14, null);
		L.RegVar("EQ_15", get_EQ_15, null);
		L.RegVar("EQ_16", get_EQ_16, null);
		L.RegVar("EQ_17", get_EQ_17, null);
		L.RegVar("EQ_18", get_EQ_18, null);
		L.RegVar("EQ_30", get_EQ_30, null);
		L.RegVar("EQ_31", get_EQ_31, null);
		L.RegVar("EQ_32", get_EQ_32, null);
		L.RegVar("EQ_33", get_EQ_33, null);
		L.RegVar("EQ_PET1", get_EQ_PET1, null);
		L.RegVar("EQ_PET2", get_EQ_PET2, null);
		L.RegVar("EQ_PET3", get_EQ_PET3, null);
		L.RegConstant("MT_INPACKAGE", 0);
		L.RegConstant("MT_PACKAGE", 1);
		L.RegConstant("MT_EQUIP", 2);
		L.RegConstant("MT_Package_F_Mythago", 3);
		L.RegConstant("MT_Package_F_Heros", 3);
		L.RegConstant("MT_BUNDLE", 4);
		L.RegConstant("MWT_DelEquip", 0);
		L.RegConstant("MWT_DelMythago", 1);
		L.RegConstant("EOM_EQMOUNT", 0);
		L.RegConstant("EOM_UNEQMOUNT", 1);
		L.RegConstant("EOM_UPMOUNT", 2);
		L.RegConstant("EOM_DOWNMOUNT", 3);
		L.RegConstant("EOM_DELMOUNT", 4);
		L.RegConstant("EOM_EQUIP_MYTHAGO", 0);
		L.RegConstant("EOM_UNEQUIP_MYTHAGO", 1);
		L.RegConstant("MOVE_INTERVAL", 300);
		L.RegConstant("JUMP_INTERVAL", 1000);
		L.RegConstant("MAX_TEAMER", 3);
		L.RegConstant("MAX_CHAT_LEN", 128);
		L.RegConstant("BUFF_SAVE_MAX", 16);
		L.RegConstant("SHORTCUT_MAX", 10);
		L.RegConstant("JumpMaxX", 8);
		L.RegConstant("JumpMaxY", 10);
		L.RegConstant("JumpAttackStopIndex", 8);
		L.RegConstant("JumpUpStopIndex", 5);
		L.RegConstant("JumpDownStopIndex", 11);
		L.RegConstant("JumpAttackStopIndex2", 3);
		L.RegConstant("JumpUpStopIndex2", 12);
		L.RegConstant("JumpDownStopIndex2", 11);
		L.RegConstant("JumpPuffStopIndex1", 14);
		L.RegConstant("JumpPuffStopIndex2", 18);
		L.RegConstant("ePK_ALL", 0);
		L.RegConstant("ePK_SAMECAMP", 1);
		L.RegConstant("ePK_DIFCAMP", 2);
		L.RegConstant("ePK_MIDCAMP", 4);
		L.RegConstant("ePK_SAMEGROUP", 4);
		L.RegConstant("ePK_SAMESCHOOL", 8);
		L.RegConstant("ePK_DIFSCHOOL", 16);
		L.RegConstant("ePK_SAMEFAC", 32);
		L.RegConstant("ePK_DIFFAC", 64);
		L.RegConstant("ePK_NOALL", 255);
		L.RegConstant("areaUTC", 480);
		L.RegConstant("nameHight", -155);
		L.RegConstant("corssType", 2);
		L.RegConstant("map_Qualifying", 512);
		L.RegConstant("map_Qualifying2", 510);
		L.RegConstant("map_FactionTowerStart", 552);
		L.RegConstant("map_FactionTowerEnd", 567);
		L.RegConstant("map_MineRob", 516);
		L.RegConstant("map_new", 3);
		L.RegConstant("map_main", 1);
		L.RegConstant("map_finish", 100000);
		L.RegConstant("map_WunQuan", 802);
		L.RegConstant("map_FF", 803);
		L.RegConstant("map_TJBX", 805);
		L.RegConstant("map_Hunt", 100000);
		L.RegConstant("map_BUYU", 100000);
		L.RegConstant("map_BUYUMain", 100000);
		L.RegConstant("map_ARENAWAIT", 100000);
		L.RegConstant("map_ARENA", 100000);
		L.RegConstant("map_LongCity", 101);
		L.RegConstant("map_SOUL", 100000);
		L.RegConstant("map_Task", 100000);
		L.RegConstant("map_factionBase", 550);
		L.RegConstant("map_factionMagic", 100000);
		L.RegConstant("map_WCZB", 515);
		L.RegConstant("map_LCYD", 523);
		L.RegConstant("map_NXLC", 525);
		L.RegConstant("map_SHUILAO_FB", 517);
		L.RegConstant("map_SHUILAO_FB1", 518);
		L.RegConstant("map_HLDT", 801);
		L.RegConstant("map_factionEscore", 100);
		L.RegConstant("map_BWZQ", 804);
		L.RegConstant("map_BWZQJS", 806);
		L.RegConstant("map_FRIST", 807);
		L.RegConstant("map_SECOND", 808);
		L.RegConstant("map_THIRD", 809);
		L.RegConstant("map_FOURTH", 810);
		L.RegConstant("map_BWZQJSFB", 520);
		L.RegConstant("map_crossCityFight", 745);
		L.RegConstant("map_Tower", 504);
		L.RegConstant("map_1v1", 622);
		L.RegConstant("map_BestServer", 625);
		L.RegConstant("map_SWBoss", 816);
		L.RegConstant("map_1v1_ready", 110);
		L.RegConstant("taskid_horse", 1054);
		L.RegConstant("taskid_money", 1181);
		L.RegConstant("taskid_awake", 2002);
		L.RegConstant("taskid_suodao", 1143);
		L.RegConstant("buffid_SanJie", 169);
		L.RegConstant("buffid_BioYs", 265);
		L.RegConstant("buffid_downHorse", 509);
		L.RegConstant("buffid_equipHorse", 216);
		L.RegConstant("buff_client", 95);
		L.RegConstant("buff_Intimacy", 86);
		L.RegConstant("buff_HP", 503);
		L.RegConstant("buff_Method1", 491);
		L.RegConstant("buff_Method2", 489);
		L.RegConstant("buff_Method3", 490);
		L.RegConstant("buff_Pro", 242);
		L.RegConstant("buff_Pro2", 459);
		L.RegConstant("buff_King", 304);
		L.RegConstant("buff_Faction", 125);
		L.RegConstant("buff_Light", 500);
		L.RegConstant("buff_Invisible", 26);
		L.RegConstant("buff_feijian", 245);
		L.RegConstant("Fashion_Marry", 9921);
		L.RegConstant("map_CBoss", 1041);
		L.RegConstant("map_ES", 1042);
		L.RegConstant("map_Treasure", 1043);
		L.RegConstant("buff_NoCross", 196);
		L.RegConstant("buff_fire", 309);
		L.RegConstant("buff_fire2", 353);
		L.RegConstant("buff_fire3", 366);
		L.RegConstant("buff_Scale", 450);
		L.RegConstant("buff_Sky", 468);
		L.RegConstant("buff_myKill", 509);
		L.RegConstant("buff_bossLight1", 126);
		L.RegConstant("buff_bossLight2", 127);
		L.RegConstant("buff_bossLight3", 128);
		L.RegConstant("buff_couplesFishing_hide", 187);
		L.RegConstant("buff_dbSite", 463);
		L.RegConstant("buff_reicarnation", 214);
		L.RegConstant("buff_reicarnationTwo", 255);
		L.RegConstant("buff_newCard", 226);
		L.RegConstant("buff_designer", 164);
		L.RegConstant("buff_scrossStone", 178);
		L.RegConstant("buff_scrossClipper", 177);
		L.RegConstant("buff_scrossCloth", 179);
		L.RegConstant("buff_frozen", 143);
		L.RegConstant("buff_spring", 130);
		L.RegConstant("buff_tower1", 276);
		L.RegConstant("buff_tower2", 277);
		L.RegConstant("map_ExpStage", 514);
		L.RegConstant("map_VipStage", 513);
		L.RegConstant("map_StoreHouseStage", 509);
		L.RegConstant("map_MapBoss", 220);
		L.RegConstant("map_SuitBoss", 223);
		L.RegConstant("map_GuildBoss", 519);
		L.RegConstant("map_GuildBoss_ID", 1022);
		L.RegConstant("Map_NewCopy", 1001);
		L.RegConstant("one_tower", 22001);
		L.RegConstant("map_FactionFlower", 551);
		L.RegConstant("map_WildBossMapOne", 221);
		L.RegConstant("map_WildBossMapTwo", 222);
		L.RegConstant("map_WildBossMapThree", 224);
		L.RegConstant("map_Dragon", 526);
		L.RegConstant("map_EquipStar", 527);
		L.RegConstant("map_couplesFishing", 528);
		L.RegConstant("couplesFishBoatNameHeight", -50);
		L.RegConstant("map_3v3PkMap1", 601);
		L.RegConstant("map_3v3PkMap2", 602);
		L.RegConstant("map_3v3PkMap3", 603);
		L.RegConstant("map_3v3PkMap4", 604);
		L.RegConstant("map_crossBossMap", 610);
		L.RegConstant("map_crossStationWoodMap", 611);
		L.RegConstant("map_crossStationIronMap", 612);
		L.RegConstant("map_crossStationBattleMap", 613);
		L.RegConstant("map_crossStationMap1", 614);
		L.RegConstant("map_crossStationMap2", 615);
		L.RegConstant("map_crossStationMap3", 616);
		L.RegConstant("map_crossStationMap4", 617);
		L.RegConstant("map_crossStationMap5", 618);
		L.RegConstant("map_crossStationBattleMapPvP", 619);
		L.RegConstant("map_factionJZ", 811);
		L.RegConstant("map_horseEquipStageMap", 529);
		L.RegConstant("map_teamEscort", 530);
		L.RegConstant("map_threeKingsSpyMap", 531);
		L.RegConstant("map_dungeonTreasureWaitMap", 621);
		L.RegConstant("map_dungeonTreasureMap", 626);
		L.RegConstant("map_wingStageMap", 532);
		L.RegConstant("map_dragonBurailMain", 812);
		L.RegConstant("map_dragonBurailBig", 813);
		L.RegConstant("map_dragonBurailSmall", 814);
		L.RegConstant("map_dragonBurailPeac", 815);
		L.RegConstant("map_shieldTaks", 817);
		L.RegConstant("map_feijianTaks", 821);
		L.RegConstant("map_Biography7_1", 713);
		L.RegConstant("map_Biography7_2", 714);
		L.RegConstant("map_Biography7_3", 715);
		L.RegConstant("map_Biography7_4", 716);
		L.RegConstant("map_Biography7_5", 717);
		L.RegConstant("map_Biography7_6", 718);
		L.RegConstant("map_biographyBWZQ", 708);
		L.RegConstant("map_biography12", 729);
		L.RegConstant("map_biographyStage5", 709);
		L.RegConstant("map_couplesGuardMap", 535);
		L.RegConstant("map_stageOpenYS", 1006);
		L.RegConstant("map_kfBWZQ", 823);
		L.RegConstant("map_crossGuardMap", 537);
		L.RegConstant("map_petIslandMapStart", 40);
		L.RegConstant("map_petIslandMapEnd", 49);
		L.RegConstant("map_petIslandMapStartL", 5401);
		L.RegConstant("map_petIslandMapEndL", 5584);
		L.RegConstant("map_newPetStageMap", 824);
		L.RegConstant("SHUILAO_ITEMS_MAX_NUM", 16);
		L.RegVar("effect_trans", get_effect_trans, null);
		L.RegVar("effect_trans2", get_effect_trans2, null);
		L.RegVar("effect_Fashion", get_effect_Fashion, null);
		L.RegVar("effect_LevelUp", get_effect_LevelUp, null);
		L.RegVar("effect_Life", get_effect_Life, null);
		L.RegVar("effect_faction1", get_effect_faction1, null);
		L.RegVar("effect_faction2", get_effect_faction2, null);
		L.RegVar("effect_faction3", get_effect_faction3, null);
		L.RegVar("effect_faction4", get_effect_faction4, null);
		L.RegVar("effect_1v1Arrow", get_effect_1v1Arrow, null);
		L.RegVar("effect_horseOn", get_effect_horseOn, null);
		L.RegVar("effect_horseDown", get_effect_horseDown, null);
		L.RegVar("effect_smoke", get_effect_smoke, null);
		L.RegVar("effect_water", get_effect_water, null);
		L.RegVar("effect_enemy", get_effect_enemy, null);
		L.RegVar("effect_Kill1", get_effect_Kill1, null);
		L.RegVar("effect_Kill2", get_effect_Kill2, null);
		L.RegVar("effect_Kill3", get_effect_Kill3, null);
		L.RegVar("effect_BWZQFM", get_effect_BWZQFM, null);
		L.RegVar("effect_LUNJIAN", get_effect_LUNJIAN, null);
		L.RegVar("effect_WEATH", get_effect_WEATH, null);
		L.RegVar("effect_HorseSkill", get_effect_HorseSkill, null);
		L.RegVar("effect_JumpDown", get_effect_JumpDown, null);
		L.RegVar("effect_AutoRoad", get_effect_AutoRoad, null);
		L.RegVar("effect_AutoFight", get_effect_AutoFight, null);
		L.RegVar("effect_Protect", get_effect_Protect, null);
		L.RegVar("effect_Hunt1", get_effect_Hunt1, null);
		L.RegVar("effect_Hunt2", get_effect_Hunt2, null);
		L.RegVar("effect_Hunt3", get_effect_Hunt3, null);
		L.RegVar("effect_Hunt4", get_effect_Hunt4, null);
		L.RegVar("effect_Flow1", get_effect_Flow1, null);
		L.RegVar("effect_Flow2", get_effect_Flow2, null);
		L.RegVar("effect_Flow3", get_effect_Flow3, null);
		L.RegVar("effect_SuitAddQ", get_effect_SuitAddQ, null);
		L.RegVar("effect_SuitSence", get_effect_SuitSence, null);
		L.RegVar("effect_SuitUI", get_effect_SuitUI, null);
		L.RegVar("effect_myCir", get_effect_myCir, null);
		L.RegVar("effect_monsterIce", get_effect_monsterIce, null);
		L.RegVar("effect_fire2", get_effect_fire2, null);
		L.RegConstant("NEW_COPY_TASKNPC", 72);
		L.RegVar("effect_hd_active", get_effect_hd_active, null);
		L.RegVar("effect_NXLC_Protect", get_effect_NXLC_Protect, null);
		L.RegVar("effect_suit_panel", get_effect_suit_panel, null);
		L.RegVar("effect_spring", get_effect_spring, null);
		L.RegVar("effect_spring_soap", get_effect_spring_soap, null);
		L.RegVar("effect_spring_soapAtc", get_effect_spring_soapAtc, null);
		L.RegVar("effect_equipstarCopy", get_effect_equipstarCopy, null);
		L.RegVar("effect_equipstarCopy2", get_effect_equipstarCopy2, null);
		L.RegVar("effect_framingPlat", get_effect_framingPlat, null);
		L.RegVar("effect_framingPlat2", get_effect_framingPlat2, null);
		L.RegVar("effect_towerBeeEffect", get_effect_towerBeeEffect, null);
		L.RegVar("effect_couplesFishingEffect", get_effect_couplesFishingEffect, null);
		L.RegVar("effect_couplesFishingAddHP", get_effect_couplesFishingAddHP, null);
		L.RegVar("effect_couplesFishing1", get_effect_couplesFishing1, null);
		L.RegVar("effect_couplesFishing2", get_effect_couplesFishing2, null);
		L.RegVar("effect_couplesFishing3", get_effect_couplesFishing3, null);
		L.RegVar("effect_bomb", get_effect_bomb, null);
		L.RegVar("effect_couplesFishingBeauty", get_effect_couplesFishingBeauty, null);
		L.RegVar("effect_MonsterDisEff", get_effect_MonsterDisEff, null);
		L.RegVar("effect_marry_male", get_effect_marry_male, null);
		L.RegVar("effect_marry_female", get_effect_marry_female, null);
		L.RegVar("effect_designer", get_effect_designer, null);
		L.RegVar("effect_designer_def", get_effect_designer_def, null);
		L.RegVar("effect_scrossStone", get_effect_scrossStone, null);
		L.RegVar("effect_scrossStone_def", get_effect_scrossStone_def, null);
		L.RegVar("effect_scrossClipper", get_effect_scrossClipper, null);
		L.RegVar("effect_scrossClipper_def", get_effect_scrossClipper_def, null);
		L.RegVar("effect_scrossCloth", get_effect_scrossCloth, null);
		L.RegVar("effect_scrossCloth_def", get_effect_scrossCloth_def, null);
		L.RegVar("effect_ClipperStoneCloth", get_effect_ClipperStoneCloth, null);
		L.RegVar("effect_factionJZ1", get_effect_factionJZ1, null);
		L.RegVar("effect_factionJZ2", get_effect_factionJZ2, null);
		L.RegVar("effect_factionJZ3", get_effect_factionJZ3, null);
		L.RegVar("effect_factionJZ4", get_effect_factionJZ4, null);
		L.RegVar("effect_factionJZ5", get_effect_factionJZ5, null);
		L.RegVar("effect_factionJZ6", get_effect_factionJZ6, null);
		L.RegVar("effect_factionJZ7", get_effect_factionJZ7, null);
		L.RegVar("effect_factionJZ8", get_effect_factionJZ8, null);
		L.RegVar("effect_factionJZ9", get_effect_factionJZ9, null);
		L.RegVar("effect_factionJZ10", get_effect_factionJZ10, null);
		L.RegVar("effect_cityFightSelf", get_effect_cityFightSelf, null);
		L.RegVar("effect_cityFightdef", get_effect_cityFightdef, null);
		L.RegVar("effect_teamEscortTian", get_effect_teamEscortTian, null);
		L.RegVar("effect_teamEscortDi", get_effect_teamEscortDi, null);
		L.RegVar("effect_teamEscortTitle", get_effect_teamEscortTitle, null);
		L.RegVar("effect_spyFirstGuard", get_effect_spyFirstGuard, null);
		L.RegVar("effect_spySecondGuard", get_effect_spySecondGuard, null);
		L.RegVar("effect_spyThirdGuard", get_effect_spyThirdGuard, null);
		L.RegVar("effect_spySkill", get_effect_spySkill, null);
		L.RegVar("effect_teamStageBoxBoom", get_effect_teamStageBoxBoom, null);
		L.RegConstant("chariot_call_buffId", 506);
		L.RegConstant("reachPointType_BHZ", 1);
		L.RegConstant("reachPointType_LCZB", 2);
		L.RegConstant("reachPointType_BWZQ", 3);
		L.RegConstant("reachPointType_LCYD", 4);
		L.RegConstant("reachPointType_NXLC", 5);
		L.RegConstant("reachPointType_LYLJ", 6);
		L.RegConstant("reachPointType_KFZD", 7);
		L.RegConstant("reachPointType_RRYZ", 8);
		L.RegConstant("reachPointType_LUNJIAN", 9);
		L.RegConstant("reachPointType_CITYFight", 10);
		L.RegConstant("stageInvateType_CT", 1);
		L.RegConstant("stageInvateType_LZ", 2);
		L.RegConstant("crossInvateType_PK", 1);
		L.RegConstant("crossInvateType_SH", 2);
		L.RegConstant("pic_xiuqiu", 3043);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNetwork_DataDefs_LYBGlobalConsts(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Network.DataDefs.LYBGlobalConsts obj = new Network.DataDefs.LYBGlobalConsts();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Network.DataDefs.LYBGlobalConsts.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int random(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
			int o = Network.DataDefs.LYBGlobalConsts.random(arg0, arg1);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ENCODE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.ENCODE);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_XYD_VERSION(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.XYD_VERSION);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ERROR_LOG_SERVER(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.ERROR_LOG_SERVER);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SCREEN_MAX_OBJECT(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, Network.DataDefs.LYBGlobalConsts.SCREEN_MAX_OBJECT);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SCREEN_MAX_PLAYER(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, Network.DataDefs.LYBGlobalConsts.SCREEN_MAX_PLAYER);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_STAND(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_STAND);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_WALK(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_WALK);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_RUN(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_RUN);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_JUMP(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_JUMP);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_JUMP2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_JUMP2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_ZAZEN(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_ZAZEN);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_ATTACKSTAND(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_ATTACKSTAND);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_STANDBIG(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_STANDBIG);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_ATTACK(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_ATTACK);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_ATTACK2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_ATTACK2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_ATTACK3(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_ATTACK3);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_WOUND(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_WOUND);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_DEAD(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_DEAD);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_RIDE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_RIDE);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_RIDEATTACK(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_RIDEATTACK);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_RIDEATTACK2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_RIDEATTACK2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_RIDEWOUND(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_RIDEWOUND);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_RIDSTAND(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_RIDSTAND);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_FLY(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_FLY);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_FLYSTAND(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_FLYSTAND);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_HORSEJUMP(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_HORSEJUMP);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_RUN2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_RUN2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_RUN3(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_RUN3);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_JUMP3(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_JUMP3);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_VILLRun(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_VILLRun);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_11(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_11);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_12(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_12);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_13(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_13);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_14(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_14);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_15(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_15);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_16(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_16);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_17(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_17);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_18(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_18);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_30(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_30);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_31(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_31);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_32(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_32);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_33(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_33);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_PET1(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_PET1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_PET2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_PET2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EQ_PET3(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.EQ_PET3);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_trans(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_trans);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_trans2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_trans2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Fashion(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Fashion);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_LevelUp(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_LevelUp);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Life(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Life);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_faction1(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_faction1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_faction2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_faction2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_faction3(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_faction3);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_faction4(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_faction4);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_1v1Arrow(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_1v1Arrow);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_horseOn(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_horseOn);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_horseDown(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_horseDown);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_smoke(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_smoke);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_water(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_water);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_enemy(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_enemy);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Kill1(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Kill1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Kill2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Kill2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Kill3(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Kill3);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_BWZQFM(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_BWZQFM);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_LUNJIAN(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_LUNJIAN);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_WEATH(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_WEATH);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_HorseSkill(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_HorseSkill);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_JumpDown(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_JumpDown);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_AutoRoad(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_AutoRoad);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_AutoFight(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_AutoFight);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Protect(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Protect);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Hunt1(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Hunt1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Hunt2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Hunt2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Hunt3(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Hunt3);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Hunt4(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Hunt4);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Flow1(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Flow1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Flow2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Flow2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_Flow3(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_Flow3);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_SuitAddQ(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_SuitAddQ);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_SuitSence(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_SuitSence);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_SuitUI(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_SuitUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_myCir(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_myCir);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_monsterIce(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_monsterIce);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_fire2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_fire2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_hd_active(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_hd_active);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_NXLC_Protect(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_NXLC_Protect);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_suit_panel(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_suit_panel);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_spring(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_spring);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_spring_soap(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_spring_soap);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_spring_soapAtc(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_spring_soapAtc);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_equipstarCopy(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_equipstarCopy);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_equipstarCopy2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_equipstarCopy2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_framingPlat(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_framingPlat);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_framingPlat2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_framingPlat2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_towerBeeEffect(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_towerBeeEffect);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_couplesFishingEffect(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_couplesFishingEffect);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_couplesFishingAddHP(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_couplesFishingAddHP);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_couplesFishing1(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_couplesFishing1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_couplesFishing2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_couplesFishing2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_couplesFishing3(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_couplesFishing3);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_bomb(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_bomb);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_couplesFishingBeauty(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_couplesFishingBeauty);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_MonsterDisEff(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_MonsterDisEff);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_marry_male(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_marry_male);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_marry_female(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_marry_female);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_designer(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_designer);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_designer_def(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_designer_def);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_scrossStone(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_scrossStone);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_scrossStone_def(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_scrossStone_def);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_scrossClipper(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_scrossClipper);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_scrossClipper_def(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_scrossClipper_def);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_scrossCloth(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_scrossCloth);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_scrossCloth_def(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_scrossCloth_def);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_ClipperStoneCloth(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_ClipperStoneCloth);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_factionJZ1(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_factionJZ1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_factionJZ2(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_factionJZ2);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_factionJZ3(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_factionJZ3);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_factionJZ4(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_factionJZ4);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_factionJZ5(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_factionJZ5);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_factionJZ6(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_factionJZ6);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_factionJZ7(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_factionJZ7);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_factionJZ8(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_factionJZ8);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_factionJZ9(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_factionJZ9);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_factionJZ10(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_factionJZ10);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_cityFightSelf(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_cityFightSelf);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_cityFightdef(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_cityFightdef);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_teamEscortTian(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_teamEscortTian);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_teamEscortDi(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_teamEscortDi);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_teamEscortTitle(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_teamEscortTitle);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_spyFirstGuard(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_spyFirstGuard);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_spySecondGuard(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_spySecondGuard);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_spyThirdGuard(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_spyThirdGuard);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_spySkill(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_spySkill);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_effect_teamStageBoxBoom(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Network.DataDefs.LYBGlobalConsts.effect_teamStageBoxBoom);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SCREEN_MAX_OBJECT(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Network.DataDefs.LYBGlobalConsts.SCREEN_MAX_OBJECT = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SCREEN_MAX_PLAYER(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Network.DataDefs.LYBGlobalConsts.SCREEN_MAX_PLAYER = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

