//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SingletonObject_ResourceManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SingletonObject<ResourceManager>), typeof(System.Object), "SingletonObject_ResourceManager");
		L.RegFunction("New", _CreateSingletonObject_ResourceManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSingletonObject_ResourceManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SingletonObject<ResourceManager> obj = new SingletonObject<ResourceManager>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SingletonObject<ResourceManager>.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, SingletonObject<ResourceManager>.Instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

